version: '2.1'

services:
  kong-database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:0.13.0
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    image: kong:0.13.0
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "nc -vz 127.0.0.1 8001 || exit 1"]
      interval: 5s
      retries: 10

  main-database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # leads-database:
  #   image: postgres:9.5
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=pass
  #     - POSTGRES_DB=db
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  setup:
    build: .
    volumes:
      - ".:/go/src/github.com/diorman/todospoc"
    depends_on:
      main-database:
        condition: service_healthy
      # leads-database:
      #   condition: service_healthy
      kong:
        condition: service_healthy
      kong-migration:
        condition: service_started
    command: go run cmd/setup/main.go

  users:
    build: .
    volumes:
      - ".:/go/src/github.com/diorman/todospoc"
    depends_on:
      setup:
        condition: service_started
    command: go run cmd/users/main.go
